image: node:8.5.0

pipelines:
  branches:
    develop:
      - step:
          caches:
            - node
          script:
            - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.0.2
            - export PATH=$HOME/.yarn/bin:$PATH
            - yarn install
            - yarn lint
            - yarn test-ci
